### PR TITLE
More perf / idiomacy optimizations

### PR DESCRIPTION
**Pull request by huitseeker**
Let me know if any particular commit isn't straightforward.

### CODE REVIEW

**Comment by jli05** [comment]
I didn't put in `optimized` for loops as I was not sure how this will work for Scala 2.11 or for future versions of Scala, and whether scalaxy is being constantly maintained or will mature. My personal feeling was that this should have been language/VM-level optimisation. So I preferred to leave it blank. Otherwise LGTM for your commits concerning HashFunctions and TensorSketch.

**Comment by huitseeker** [comment]
Sadly, the language / VM level optim is not to be : the discussion of optimizing the performance of scala's for comprehensions has gone on *ad nauseam* since they existed (see [here](https://issues.scala-lang.org/browse/SI-1338) for a recent, 2008 instance), and has always been faced with a strict refusal.

[Scalaxy-loops](https://github.com/nativelibs4java/Scalaxy/tree/master/Loops) is a portable, conservative, minimal fragment of [Scalaxy](https://github.com/nativelibs4java/Scalaxy) which is compatible with 2.10 & 2.11 (as you can check, cross-building, issuing 'sbt +package'). It proceeds through a <200 lines whitebox macro, so quite maintainable. If it becomes incompatible / unmaintained, rolling back of the 'optimized' stanza is always available, bringing us back to the starting point of today.

**Comment by FurongHuang** [comment]
Hi Francois,
Thank you for your inputs!
Sorry for the delay, I was in the middle of submitting for nips, my
dissertation and preparing for my defense coming soon. I will take a look
at things after next Monday!


Best regards,

Furong Huang
=============
PhD Candidate
UC Irvine

On May 19, 2016, at 14:13, François Garillot <notifications@github.com>
wrote:

Let me know if any particular commit isn't straightforward.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12
Commit Summary

   - Make LDAExample a bit more idiomatic
   - Make prints in SpectralLDA more idiomatic
   - help a bit with the index dependence in Tensorsketch
   - Avoid '.get' in HashFunctions
   - More straightforward optimizations / cleanups
   - Update dependencies

File Changes

   - *M* build.sbt
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-0>
   (4)
   - *M* src/main/scala/edu/uci/eecs/spectralLDA/LDAExample.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-1>
   (91)
   - *M* src/main/scala/edu/uci/eecs/spectralLDA/SpectralLDA.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-2>
   (38)
   - *M*
   src/main/scala/edu/uci/eecs/spectralLDA/datamoments/DataCumulant.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-3>
   (2)
   - *M*
   src/main/scala/edu/uci/eecs/spectralLDA/datamoments/DataCumulantSketch.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-4>
   (2)
   - *M* src/main/scala/edu/uci/eecs/spectralLDA/sketch/HashFunctions.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-5>
   (6)
   - *M* src/main/scala/edu/uci/eecs/spectralLDA/sketch/TensorSketch.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-6>
   (8)
   - *M* src/main/scala/edu/uci/eecs/spectralLDA/utils/AlgebraUtil.scala
   <https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12/files#diff-7>
   (10)

Patch Links:

   - https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12.patch
   - https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/12>

**Comment by jli05** [comment]
@huitseeker I found [Scalaxy/Streams](https://github.com/nativelibs4java/scalaxy-streams ) which is for Scala 2.11 and the heir to Scalaxy/Loops. Would you share any comments/experiences on Scalaxy/Streams vs Scalaxy/Loops?

**Comment by huitseeker** [comment]
I'm a huge fan, but having done some profiling of the LDA task for https://github.com/FurongHuang/SpectralLDA-TensorSpark/pull/2 (with YourKit I think), I noticed the only significant improvements were in the integer-indexed for loops. See also this:
https://speakerdeck.com/ichoran/designing-for-performance-scala-days-2013?slide=65
for why it's less urgent for other collection methods. 

In sum, if you want to try to switch from scalaxy/loops to scalaxy/streams, i think it my be worth to at least profile the job and investigate. We'll always learn something useful of the profiling. But that should be done in another PR I think.

**Comment by FurongHuang** [comment]
Hi, it seems that there is conflict in "DataCumulantSketch.scala".
<<<<<<< HEAD
    val firstOrderMoments_whitened = W.t * firstOrderMoments

    val broadcasted_W = sc.broadcast(W)
    val broadcasted_sketcher = sc.broadcast(sketcher)

    val fft_Ta: DenseMatrix[Complex] = validDocuments
      .map {
        case (_, len, vec) => update_thirdOrderMoments(
          alpha0,
          broadcasted_W.value,
          firstOrderMoments_whitened,
          vec, len,
          broadcasted_sketcher.value)
      }
      .reduce(_ + _)
      .map(_ / numDocs.toDouble)
=======
    val Ta: DenseMatrix[Double] = whitenedData map {
      case (vec, len) => update_thirdOrderMoments(
        dimK, alpha0,
        firstOrderMoments_whitened,
        vec, len)
    } reduce(_ + _)
>>>>>>> 138f7c825aac2e427c55ab49e697bbe5f2a2d9af

What do you think?

**Comment by huitseeker** [comment]
@FurongHuang : no conflict that I could see -  and I expect the Github UI would have shown it if it were the case.

Perhaps a conflict with one of your local changes when trying to pull the branch ?

**Pull request merged**
